## Data Exploration

In [1606]:
import pandas as pd
df=pd.read_csv('/Users/hindsalem/Desktop/tempjjh/Sheet 2-Table 1.csv')

In [1607]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD + 1TB HDD,Intel Iris Plus Graphics 640,macOS,1.37kg,3568.934
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,2394.776
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,1531.800
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,6759.767
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,4804.790
...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,1.64kg,2075.256
1004,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.2kg,3183.480
1005,HP,Notebook,14.0,1366x768,Intel Core i5 6300U 2.4GHz,4GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.48kg,2930.373
1006,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg,3210.120
1007,HP,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.43kg,3860.136

In [1608]:
df.duplicated().sum()

0

In [1609]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [1610]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1008 non-null   object
 1   TypeName          1008 non-null   object
 2   Inches            1008 non-null   float64
 3   ScreenResolution  1008 non-null   object
 4   Cpu               1008 non-null   object
 5   Ram               1008 non-null   object
 6   Memory            1008 non-null   object
 7   Gpu               1008 non-null   object
 8   OpSys             1008 non-null   object
 9   Weight            1008 non-null   object
 10  Price             1008 non-null   float64
dtypes: float64(2), object(9)
memory usage: 86.8+ KB

## Feature Engineering

In [1611]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD + 1TB HDD,Intel Iris Plus Graphics 640,macOS,1.37kg,3568.934
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,2394.776
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,1531.800
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,6759.767
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,4804.790
...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,1.64kg,2075.256
1004,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.2kg,3183.480
1005,HP,Notebook,14.0,1366x768,Intel Core i5 6300U 2.4GHz,4GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.48kg,2930.373
1006,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg,3210.120
1007,HP,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.43kg,3860.136

In [1612]:
df.Ram=df.Ram.str.replace('GB','').astype(float)
df.Weight=df.Weight.str.replace('kg','').astype(float)

In [1613]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1008 non-null   object
 1   TypeName          1008 non-null   object
 2   Inches            1008 non-null   float64
 3   ScreenResolution  1008 non-null   object
 4   Cpu               1008 non-null   object
 5   Ram               1008 non-null   float64
 6   Memory            1008 non-null   object
 7   Gpu               1008 non-null   object
 8   OpSys             1008 non-null   object
 9   Weight            1008 non-null   float64
 10  Price             1008 non-null   float64
dtypes: float64(4), object(7)
memory usage: 86.8+ KB

In [1614]:
df['IPS']=df['ScreenResolution'].apply(lambda ips: 1 if 'IPS' in ips else 0)

In [1615]:
df['Touchscreen']=df.ScreenResolution.apply(lambda val_of_serise: 1 if 'Touchscreen'in val_of_serise else 0)

In [1616]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8.0,128GB SSD + 1TB HDD,Intel Iris Plus Graphics 640,macOS,1.37,3568.934,1,0
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,2394.776,0,0
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,No OS,1.86,1531.800,0,0
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16.0,512GB SSD,AMD Radeon Pro 455,macOS,1.83,6759.767,1,0
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8.0,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,4804.790,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4.0,500GB HDD,Intel HD Graphics 620,Windows 10,1.64,2075.256,0,0
1004,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4.0,128GB SSD,Intel HD Graphics 520,Windows 10,1.20,3183.480,0,0
1005,HP,Notebook,14.0,1366x768,Intel Core i5 6300U 2.4GHz,4.0,256GB SSD,Intel HD Graphics 520,Windows 10,1.48,2930.373,0,0
1006,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4.0,256GB SSD,Intel HD Graphics 620,Windows 10,1.95,3210.120,0,0
1007,HP,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.43,3860.136,0,0

In [1617]:
Accuracy=df['ScreenResolution'].str.split('x',expand=True)
# Accuracy
df['X']=Accuracy[0]

df['Y']=Accuracy[1]

In [1618]:
len(df['X'])

1008

In [1619]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen,X,Y
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8.0,128GB SSD + 1TB HDD,Intel Iris Plus Graphics 640,macOS,1.37,3568.934,1,0,IPS Panel Retina Display 2560,1600
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,2394.776,0,0,1440,900
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,No OS,1.86,1531.800,0,0,Full HD 1920,1080
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16.0,512GB SSD,AMD Radeon Pro 455,macOS,1.83,6759.767,1,0,IPS Panel Retina Display 2880,1800
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8.0,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,4804.790,1,0,IPS Panel Retina Display 2560,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4.0,500GB HDD,Intel HD Graphics 620,Windows 10,1.64,2075.256,0,0,1366,768
1004,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4.0,128GB SSD,Intel HD Graphics 520,Windows 10,1.20,3183.480,0,0,Full HD 1920,1080
1005,HP,Notebook,14.0,1366x768,Intel Core i5 6300U 2.4GHz,4.0,256GB SSD,Intel HD Graphics 520,Windows 10,1.48,2930.373,0,0,1366,768
1006,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4.0,256GB SSD,Intel HD Graphics 620,Windows 10,1.95,3210.120,0,0,Full HD 1920,1080
1007,HP,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.43,3860.136,0,0,Full HD 1920,1080

In [1620]:
st=df.X.str.findall(r'(\d+\.?\d+)').apply(lambda x: x[0])
df.X=st

In [1621]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen,X,Y
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8.0,128GB SSD + 1TB HDD,Intel Iris Plus Graphics 640,macOS,1.37,3568.934,1,0,2560,1600
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,2394.776,0,0,1440,900
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,No OS,1.86,1531.800,0,0,1920,1080
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16.0,512GB SSD,AMD Radeon Pro 455,macOS,1.83,6759.767,1,0,2880,1800
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8.0,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,4804.790,1,0,2560,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4.0,500GB HDD,Intel HD Graphics 620,Windows 10,1.64,2075.256,0,0,1366,768
1004,Toshiba,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4.0,128GB SSD,Intel HD Graphics 520,Windows 10,1.20,3183.480,0,0,1920,1080
1005,HP,Notebook,14.0,1366x768,Intel Core i5 6300U 2.4GHz,4.0,256GB SSD,Intel HD Graphics 520,Windows 10,1.48,2930.373,0,0,1366,768
1006,HP,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4.0,256GB SSD,Intel HD Graphics 620,Windows 10,1.95,3210.120,0,0,1920,1080
1007,HP,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 6600U 2.6GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.43,3860.136,0,0,1920,1080

In [1622]:
df.X=df.X.astype(int)
df.Y=df.Y.astype(int)

In [1623]:
len(df.Y.unique())

10

In [1624]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           1008 non-null   object
 1   TypeName          1008 non-null   object
 2   Inches            1008 non-null   float64
 3   ScreenResolution  1008 non-null   object
 4   Cpu               1008 non-null   object
 5   Ram               1008 non-null   float64
 6   Memory            1008 non-null   object
 7   Gpu               1008 non-null   object
 8   OpSys             1008 non-null   object
 9   Weight            1008 non-null   float64
 10  Price             1008 non-null   float64
 11  IPS               1008 non-null   int64
 12  Touchscreen       1008 non-null   int64
 13  X                 1008 non-null   int64
 14  Y                 1008 non-null   int64
dtypes: float64(4), int64(4), object(7)
memory usage: 118.2+ KB

In [1625]:
df.corr()['Price']

Inches         0.070039
Ram            0.762323
Weight         0.218461
Price          1.000000
IPS            0.233671
Touchscreen    0.206682
X              0.577292
Y              0.575234
Name: Price, dtype: float64

In [1626]:
df['ppi']=((((df.X)**2)+((df.Y)**2)**0.5)/(df.Inches))

In [1627]:
df['ppi']

0       492872.180451
1       155977.443609
2       236376.923077
3       538714.285714
4       492872.180451
            ...
1003    133337.428571
1004    277254.135338
1005    133337.428571
1006    263391.428571
1007    263391.428571
Name: ppi, Length: 1008, dtype: float64

In [1628]:
df.corr()['Price']

Inches         0.070039
Ram            0.762323
Weight         0.218461
Price          1.000000
IPS            0.233671
Touchscreen    0.206682
X              0.577292
Y              0.575234
ppi            0.507678
Name: Price, dtype: float64

In [1629]:
df.drop(columns=['ScreenResolution'],inplace=True)
df

,Company,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,IPS,Touchscreen,X,Y,ppi
0,Apple,Ultrabook,13.3,Intel Core i5 2.3GHz,8.0,128GB SSD + 1TB HDD,Intel Iris Plus Graphics 640,macOS,1.37,3568.934,1,0,2560,1600,492872.180451
1,Apple,Ultrabook,13.3,Intel Core i5 1.8GHz,8.0,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,2394.776,0,0,1440,900,155977.443609
2,HP,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8.0,256GB SSD,Intel HD Graphics 620,No OS,1.86,1531.800,0,0,1920,1080,236376.923077
3,Apple,Ultrabook,15.4,Intel Core i7 2.7GHz,16.0,512GB SSD,AMD Radeon Pro 455,macOS,1.83,6759.767,1,0,2880,1800,538714.285714
4,Apple,Ultrabook,13.3,Intel Core i5 3.1GHz,8.0,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,4804.790,1,0,2560,1600,492872.180451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,Intel Core i5 7200U 2.5GHz,4.0,500GB HDD,Intel HD Graphics 620,Windows 10,1.64,2075.256,0,0,1366,768,133337.428571
1004,Toshiba,Notebook,13.3,Intel Core i5 6200U 2.3GHz,4.0,128GB SSD,Intel HD Graphics 520,Windows 10,1.20,3183.480,0,0,1920,1080,277254.135338
1005,HP,Notebook,14.0,Intel Core i5 6300U 2.4GHz,4.0,256GB SSD,Intel HD Graphics 520,Windows 10,1.48,2930.373,0,0,1366,768,133337.428571
1006,HP,Notebook,14.0,Intel Core i5 7200U 2.5GHz,4.0,256GB SSD,Intel HD Graphics 620,Windows 10,1.95,3210.120,0,0,1920,1080,263391.428571
1007,HP,Ultrabook,14.0,Intel Core i7 6600U 2.6GHz,8.0,256GB SSD,Intel HD Graphics 520,Windows 7,1.43,3860.136,0,0,1920,1080,263391.428571

In [1630]:
 df['Cpu']= df['Cpu'].apply(lambda x:" ".join(x.split()[0:3]))

In [1631]:
def processor(text):
    if text == 'Intel Core i7' or text == 'Intel Core i5' or text == 'Intel Core i3':
        return text
    else:
        if text.split()[0] == 'Intel':
            return 'Other Intel Processor'
        else:
            return 'AMD Processor'

In [1632]:
df['Cpu'] = df['Cpu'].apply(processor)

In [1633]:
df['Cpu'].value_counts()

Intel Core i7            397
Intel Core i5            344
Other Intel Processor    111
Intel Core i3            107
AMD Processor             49
Name: Cpu, dtype: int64

In [1634]:
df['Memory'].value_counts()

256GB SSD                       328
1TB HDD                         174
512GB SSD                        94
500GB HDD                        83
128GB SSD + 1TB HDD              75
128GB SSD                        66
256GB SSD + 1TB HDD              54
32GB Flash Storage               29
2TB HDD                          14
512GB SSD + 1TB HDD              13
1TB SSD                          11
256GB SSD + 2TB HDD              10
64GB Flash Storage                9
16GB Flash Storage                6
32GB SSD                          5
256GB Flash Storage               5
128GB Flash Storage               4
180GB SSD                         4
512GB SSD + 2TB HDD               3
16GB SSD                          2
256GB SSD + 256GB SSD             2
1TB SSD + 1TB HDD                 2
128GB SSD + 2TB HDD               2
64GB SSD                          1
512GB SSD + 256GB SSD             1
32GB HDD                          1
1TB HDD + 1TB HDD                 1
256GB SSD + 500GB HDD             1
128GB HDD                         1
508GB Hybrid                      1
64GB Flash Storage + 1TB HDD      1
8GB SSD                           1
512GB Flash Storage               1
512GB SSD + 512GB SSD             1
240GB SSD                         1
1.0TB Hybrid                      1
Name: Memory, dtype: int64

In [1635]:
df["Memory"] = df["Memory"].str.replace('GB', '')
df["Memory"] = df["Memory"].str.replace('TB', '000')
new = df["Memory"].str.split("+", n = 1, expand = True)

df["first"]= new[0]
df["first"]=df["first"].str.strip()

df["second"]= new[1]

df["Layer1HDD"] = df["first"].apply(lambda x: 1 if "HDD" in x else 0)
df["Layer1SSD"] = df["first"].apply(lambda x: 1 if "SSD" in x else 0)
df["Layer1Hybrid"] = df["first"].apply(lambda x: 1 if "Hybrid" in x else 0)

df['first'] = df['first'].str.replace(r'\D', '')

df["second"].fillna("0", inplace = True)

df["Layer2HDD"] = df["second"].apply(lambda x: 1 if "HDD" in x else 0)
df["Layer2SSD"] = df["second"].apply(lambda x: 1 if "SSD" in x else 0)

# df["second"]
df["first"] = df["first"].astype(int)

df["second"] = df["second"].str.replace('HDD','')
df["second"]=df["second"].str.replace('SSD','').astype(int)
df["HDD"]=(df["first"]*df["Layer1HDD"]+df["second"]*df["Layer2HDD"])
df["SSD"]=(df["first"]*df["Layer1SSD"]+df["second"]*df["Layer2SSD"])


df.drop(columns=['first', 'second', 'Layer1HDD', 'Layer1SSD', 'Layer2HDD', 'Layer2SSD','Memory'],inplace=True)

<ipython-input-1635-7c23bb7e4e72>:14: FutureWarning: The default value of regex will change from True to False in a future version.
  df['first'] = df['first'].str.replace(r'\D', '')

In [1636]:
df

,Company,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price,IPS,Touchscreen,X,Y,ppi,Layer1Hybrid,HDD,SSD
0,Apple,Ultrabook,13.3,Intel Core i5,8.0,Intel Iris Plus Graphics 640,macOS,1.37,3568.934,1,0,2560,1600,492872.180451,0,1000,128
1,Apple,Ultrabook,13.3,Intel Core i5,8.0,Intel HD Graphics 6000,macOS,1.34,2394.776,0,0,1440,900,155977.443609,0,0,0
2,HP,Notebook,15.6,Intel Core i5,8.0,Intel HD Graphics 620,No OS,1.86,1531.800,0,0,1920,1080,236376.923077,0,0,256
3,Apple,Ultrabook,15.4,Intel Core i7,16.0,AMD Radeon Pro 455,macOS,1.83,6759.767,1,0,2880,1800,538714.285714,0,0,512
4,Apple,Ultrabook,13.3,Intel Core i5,8.0,Intel Iris Plus Graphics 650,macOS,1.37,4804.790,1,0,2560,1600,492872.180451,0,0,256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,Intel Core i5,4.0,Intel HD Graphics 620,Windows 10,1.64,2075.256,0,0,1366,768,133337.428571,0,500,0
1004,Toshiba,Notebook,13.3,Intel Core i5,4.0,Intel HD Graphics 520,Windows 10,1.20,3183.480,0,0,1920,1080,277254.135338,0,0,128
1005,HP,Notebook,14.0,Intel Core i5,4.0,Intel HD Graphics 520,Windows 10,1.48,2930.373,0,0,1366,768,133337.428571,0,0,256
1006,HP,Notebook,14.0,Intel Core i5,4.0,Intel HD Graphics 620,Windows 10,1.95,3210.120,0,0,1920,1080,263391.428571,0,0,256
1007,HP,Ultrabook,14.0,Intel Core i7,8.0,Intel HD Graphics 520,Windows 7,1.43,3860.136,0,0,1920,1080,263391.428571,0,0,256

In [1637]:
df

,Company,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price,IPS,Touchscreen,X,Y,ppi,Layer1Hybrid,HDD,SSD
0,Apple,Ultrabook,13.3,Intel Core i5,8.0,Intel Iris Plus Graphics 640,macOS,1.37,3568.934,1,0,2560,1600,492872.180451,0,1000,128
1,Apple,Ultrabook,13.3,Intel Core i5,8.0,Intel HD Graphics 6000,macOS,1.34,2394.776,0,0,1440,900,155977.443609,0,0,0
2,HP,Notebook,15.6,Intel Core i5,8.0,Intel HD Graphics 620,No OS,1.86,1531.800,0,0,1920,1080,236376.923077,0,0,256
3,Apple,Ultrabook,15.4,Intel Core i7,16.0,AMD Radeon Pro 455,macOS,1.83,6759.767,1,0,2880,1800,538714.285714,0,0,512
4,Apple,Ultrabook,13.3,Intel Core i5,8.0,Intel Iris Plus Graphics 650,macOS,1.37,4804.790,1,0,2560,1600,492872.180451,0,0,256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,HP,Notebook,14.0,Intel Core i5,4.0,Intel HD Graphics 620,Windows 10,1.64,2075.256,0,0,1366,768,133337.428571,0,500,0
1004,Toshiba,Notebook,13.3,Intel Core i5,4.0,Intel HD Graphics 520,Windows 10,1.20,3183.480,0,0,1920,1080,277254.135338,0,0,128
1005,HP,Notebook,14.0,Intel Core i5,4.0,Intel HD Graphics 520,Windows 10,1.48,2930.373,0,0,1366,768,133337.428571,0,0,256
1006,HP,Notebook,14.0,Intel Core i5,4.0,Intel HD Graphics 620,Windows 10,1.95,3210.120,0,0,1920,1080,263391.428571,0,0,256
1007,HP,Ultrabook,14.0,Intel Core i7,8.0,Intel HD Graphics 520,Windows 7,1.43,3860.136,0,0,1920,1080,263391.428571,0,0,256

## TO DUMMAY

In [1638]:
# Company,TypeName,Cpu,Gpu,OpSys,HDD,SSD

In [1639]:
df.Gpu.sort_values

<bound method Series.sort_values of 0       Intel Iris Plus Graphics 640
1             Intel HD Graphics 6000
2              Intel HD Graphics 620
3                 AMD Radeon Pro 455
4       Intel Iris Plus Graphics 650
                    ...
1003           Intel HD Graphics 620
1004           Intel HD Graphics 520
1005           Intel HD Graphics 520
1006           Intel HD Graphics 620
1007           Intel HD Graphics 520
Name: Gpu, Length: 1008, dtype: object>

In [1640]:
df['Gpu']=df['Gpu'].apply(lambda x : x.split()[0])

In [1641]:
df.Gpu.value_counts()

Intel     547
Nvidia    315
AMD       146
Name: Gpu, dtype: int64

In [1642]:
Cpu= pd.get_dummies(df["Cpu"])
Cpu

,AMD Processor,Intel Core i3,Intel Core i5,Intel Core i7,Other Intel Processor
0,0,0,1,0,0
1,0,0,1,0,0
2,0,0,1,0,0
3,0,0,0,1,0
4,0,0,1,0,0
...,...,...,...,...,...
1003,0,0,1,0,0
1004,0,0,1,0,0
1005,0,0,1,0,0
1006,0,0,1,0,0
1007,0,0,0,1,0

In [1643]:
Company= pd.get_dummies(df["Company"])
Company

,Acer,Apple,Asus,Chuwi,Dell,Fujitsu,Google,HP,Huawei,LG,Lenovo,MSI,Mediacom,Microsoft,Razer,Samsung,Toshiba,Vero,Xiaomi
0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1005,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1006,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1007,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

In [1644]:
Ram= pd.get_dummies(df["Ram"])
Ram

      2.0   4.0   6.0   8.0   12.0  16.0  24.0  32.0
0        0     0     0     1     0     0     0     0
1        0     0     0     1     0     0     0     0
2        0     0     0     1     0     0     0     0
3        0     0     0     0     0     1     0     0
4        0     0     0     1     0     0     0     0
...    ...   ...   ...   ...   ...   ...   ...   ...
1003     0     1     0     0     0     0     0     0
1004     0     1     0     0     0     0     0     0
1005     0     1     0     0     0     0     0     0
1006     0     1     0     0     0     0     0     0
1007     0     0     0     1     0     0     0     0

[1008 rows x 8 columns]

In [1645]:
TypeName= pd.get_dummies(df["TypeName"])
TypeName

      2 in 1 Convertible  Gaming  Netbook  Notebook  Ultrabook  Workstation
0                      0       0        0         0          1            0
1                      0       0        0         0          1            0
2                      0       0        0         1          0            0
3                      0       0        0         0          1            0
4                      0       0        0         0          1            0
...                  ...     ...      ...       ...        ...          ...
1003                   0       0        0         1          0            0
1004                   0       0        0         1          0            0
1005                   0       0        0         1          0            0
1006                   0       0        0         1          0            0
1007                   0       0        0         0          1            0

[1008 rows x 6 columns]

In [1646]:
OpSys= pd.get_dummies(df["OpSys"])
OpSys

,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS
0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
1003,0,0,0,0,0,1,0,0,0
1004,0,0,0,0,0,1,0,0,0
1005,0,0,0,0,0,1,0,0,0
1006,0,0,0,0,0,1,0,0,0
1007,0,0,0,0,0,0,0,1,0

In [1647]:
Gpu= pd.get_dummies(df["Gpu"])
Gpu

      AMD  Intel  Nvidia
0       0      1       0
1       0      1       0
2       0      1       0
3       1      0       0
4       0      1       0
...   ...    ...     ...
1003    0      1       0
1004    0      1       0
1005    0      1       0
1006    0      1       0
1007    0      1       0

[1008 rows x 3 columns]

In [1648]:
HDD=pd.get_dummies(df["HDD"]) 
HDD

      0     32    128   500   1000  2000
0        0     0     0     0     1     0
1        1     0     0     0     0     0
2        1     0     0     0     0     0
3        1     0     0     0     0     0
4        1     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...
1003     0     0     0     1     0     0
1004     1     0     0     0     0     0
1005     1     0     0     0     0     0
1006     1     0     0     0     0     0
1007     1     0     0     0     0     0

[1008 rows x 6 columns]

In [1649]:
X=pd.get_dummies(df["X"]) 
X

,1366,1440,1600,1920,2160,2256,2304,2400,2560,2736,2880,3200,3840
0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,1,0,0,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,1,0,0,0,0,0,0,0,0,0
1005,1,0,0,0,0,0,0,0,0,0,0,0,0
1006,0,0,0,1,0,0,0,0,0,0,0,0,0
1007,0,0,0,1,0,0,0,0,0,0,0,0,0

In [1650]:
Y=pd.get_dummies(df["Y"]) 
Y

      768   900   1080  1200  1440  1504  1600  1800  1824  2160
0        0     0     0     0     0     0     1     0     0     0
1        0     1     0     0     0     0     0     0     0     0
2        0     0     1     0     0     0     0     0     0     0
3        0     0     0     0     0     0     0     1     0     0
4        0     0     0     0     0     0     1     0     0     0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
1003     1     0     0     0     0     0     0     0     0     0
1004     0     0     1     0     0     0     0     0     0     0
1005     1     0     0     0     0     0     0     0     0     0
1006     0     0     1     0     0     0     0     0     0     0
1007     0     0     1     0     0     0     0     0     0     0

[1008 rows x 10 columns]

In [1651]:
SSD=pd.get_dummies(df["SSD"]) 
SSD

,0,8,16,32,64,128,180,240,256,512,768,1000,1024
0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,1,0,0,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,1,0,0,0,0,0,0,0
1005,0,0,0,0,0,0,0,0,1,0,0,0,0
1006,0,0,0,0,0,0,0,0,1,0,0,0,0
1007,0,0,0,0,0,0,0,0,1,0,0,0,0

In [1652]:
df.drop(columns= ['Company','TypeName','Cpu','Gpu','OpSys','HDD','SSD','X','Y','Ram'], inplace=True)

In [1660]:
df1=pd.concat([Company,TypeName,Cpu,Gpu,OpSys,HDD,SSD,df,Ram], axis=1)
df1

,Acer,Apple,Asus,Chuwi,Dell,Fujitsu,Google,HP,Huawei,LG,...,ppi,Layer1Hybrid,2.0,4.0,6.0,8.0,12.0,16.0,24.0,32.0
0,0,1,0,0,0,0,0,0,0,0,...,492872.180451,0,0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,155977.443609,0,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,236376.923077,0,0,0,0,1,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,538714.285714,0,0,0,0,0,0,1,0,0
4,0,1,0,0,0,0,0,0,0,0,...,492872.180451,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,0,0,0,0,0,0,0,1,0,0,...,133337.428571,0,0,1,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,277254.135338,0,0,1,0,0,0,0,0,0
1005,0,0,0,0,0,0,0,1,0,0,...,133337.428571,0,0,1,0,0,0,0,0,0
1006,0,0,0,0,0,0,0,1,0,0,...,263391.428571,0,0,1,0,0,0,0,0,0
1007,0,0,0,0,0,0,0,1,0,0,...,263391.428571,0,0,0,0,1,0,0,0,0

In [1654]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 68 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Acer                   1008 non-null   uint8
 1   Apple                  1008 non-null   uint8
 2   Asus                   1008 non-null   uint8
 3   Chuwi                  1008 non-null   uint8
 4   Dell                   1008 non-null   uint8
 5   Fujitsu                1008 non-null   uint8
 6   Google                 1008 non-null   uint8
 7   HP                     1008 non-null   uint8
 8   Huawei                 1008 non-null   uint8
 9   LG                     1008 non-null   uint8
 10  Lenovo                 1008 non-null   uint8
 11  MSI                    1008 non-null   uint8
 12  Mediacom               1008 non-null   uint8
 13  Microsoft              1008 non-null   uint8
 14  Razer                  1008 non-null   uint8
 15  Samsung                1008 non-null   uint8
 16  Toshiba                1008 non-null   uint8
 17  Vero                   1008 non-null   uint8
 18  Xiaomi                 1008 non-null   uint8
 19  2 in 1 Convertible     1008 non-null   uint8
 20  Gaming                 1008 non-null   uint8
 21  Netbook                1008 non-null   uint8
 22  Notebook               1008 non-null   uint8
 23  Ultrabook              1008 non-null   uint8
 24  Workstation            1008 non-null   uint8
 25  AMD Processor          1008 non-null   uint8
 26  Intel Core i3          1008 non-null   uint8
 27  Intel Core i5          1008 non-null   uint8
 28  Intel Core i7          1008 non-null   uint8
 29  Other Intel Processor  1008 non-null   uint8
 30  AMD                    1008 non-null   uint8
 31  Intel                  1008 non-null   uint8
 32  Nvidia                 1008 non-null   uint8
 33  Android                1008 non-null   uint8
 34  Chrome OS              1008 non-null   uint8
 35  Linux                  1008 non-null   uint8
 36  Mac OS X               1008 non-null   uint8
 37  No OS                  1008 non-null   uint8
 38  Windows 10             1008 non-null   uint8
 39  Windows 10 S           1008 non-null   uint8
 40  Windows 7              1008 non-null   uint8
 41  macOS                  1008 non-null   uint8
 42  0                      1008 non-null   uint8
 43  32                     1008 non-null   uint8
 44  128                    1008 non-null   uint8
 45  500                    1008 non-null   uint8
 46  1000                   1008 non-null   uint8
 47  2000                   1008 non-null   uint8
 48  0                      1008 non-null   uint8
 49  8                      1008 non-null   uint8
 50  16                     1008 non-null   uint8
 51  32                     1008 non-null   uint8
 52  64                     1008 non-null   uint8
 53  128                    1008 non-null   uint8
 54  180                    1008 non-null   uint8
 55  240                    1008 non-null   uint8
 56  256                    1008 non-null   uint8
 57  512                    1008 non-null   uint8
 58  768                    1008 non-null   uint8
 59  1000                   1008 non-null   uint8
 60  1024                   1008 non-null   uint8
 61  Inches                 1008 non-null   float64
 62  Weight                 1008 non-null   float64
 63  Price                  1008 non-null   float64
 64  IPS                    1008 non-null   int64
 65  Touchscreen            1008 non-null   int64
 66  ppi                    1008 non-null   float64
 67  Layer1Hybrid           1008 non-null   int64
dtypes: float64(4), int64(3), uint8(61)
memory usage: 115.3 KB

In [1655]:
# اقل من ٢٠٠٠ كروس فلاديشن

In [1656]:
df1.isnull().sum()

Acer            0
Apple           0
Asus            0
Chuwi           0
Dell            0
               ..
Price           0
IPS             0
Touchscreen     0
ppi             0
Layer1Hybrid    0
Length: 68, dtype: int64

In [1657]:
df.duplicated().sum()

17

In [1658]:
laptop_Data=df1.to_csv('laptop_Data.csv')

df1

In [1659]:
df1

,Acer,Apple,Asus,Chuwi,Dell,Fujitsu,Google,HP,Huawei,LG,...,768,1000,1024,Inches,Weight,Price,IPS,Touchscreen,ppi,Layer1Hybrid
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,13.3,1.37,3568.934,1,0,492872.180451,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,13.3,1.34,2394.776,0,0,155977.443609,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,15.6,1.86,1531.800,0,0,236376.923077,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,15.4,1.83,6759.767,1,0,538714.285714,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,13.3,1.37,4804.790,1,0,492872.180451,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,0,0,0,0,0,0,0,1,0,0,...,0,0,0,14.0,1.64,2075.256,0,0,133337.428571,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,13.3,1.20,3183.480,0,0,277254.135338,0
1005,0,0,0,0,0,0,0,1,0,0,...,0,0,0,14.0,1.48,2930.373,0,0,133337.428571,0
1006,0,0,0,0,0,0,0,1,0,0,...,0,0,0,14.0,1.95,3210.120,0,0,263391.428571,0
1007,0,0,0,0,0,0,0,1,0,0,...,0,0,0,14.0,1.43,3860.136,0,0,263391.428571,0